### PR TITLE
Get rid of unsafe in entry

### PR DESCRIPTION
**Pull request by birkenfeld**
This isn't the most efficient way to do it - I can't imagine the index checks are all elided - but it works without unsafe, which should be a priority for this demo crate.

Nice stream BTW! One topic for another day could be to take one of the minor "sad" things and create a patch/PR to rustc on stream :smile:

### CODE REVIEW

**Comment by jonhoo** [comment]
Ah, yes, that's much nicer, thank you!

While I think that is a great idea, I also worry that it would be very long for a single stream. There's also the issue that I don't know the rustc code all that well, and reading up on something as large as the Rust compiler will be tricky to pull off live :p

**Comment by jonhoo** [comment]
Oh, and for posterity, see @nikomatsakis's response here: https://twitter.com/nikomatsakis/status/1003238711881076739

**Comment by birkenfeld** [comment]
Good to know it'll eventually be resolved!

**Comment by dvic** [comment]
It seems this is indeed the only way to solve it, here is an in-depth explanation (more or less exactly the same situation): http://smallcultfollowing.com/babysteps/blog/2016/04/27/non-lexical-lifetimes-introduction/#problem-case-3-conditional-control-flow-across-functions

**Pull request merged**
